#pragma once

// GCC 11 SSO Coroutine Safety — see docs/contributing.rst "Known Issues" for full details.
// Do NOT store std::string in a coroutine frame across co_await (GCC bugs #107288/#100611).
// Named patterns referenced at each call site below:
//   [not-a-coroutine]    Public methods with std::string params are plain functions; they
//                        serialise inputs before delegating to the real coroutine.
//   [string_view]        Use std::string_view (trivially copyable) for coroutine method params.
//   [int64-id]           Keep request IDs as int64_t across suspensions; rebuild string after.
//   [scope-before-await] Build SSO-risky objects in {}, serialise to wire string, then co_await.
//   [wire-builders]      make_result_wire/make_error_wire are synchronous helpers;
//                        do NOT convert them to Task<T> coroutines.

#include <mcp/core/concepts.hpp>
#include <mcp/core/core.hpp>
#include <mcp/core/export.hpp>
#include <mcp/protocol/protocol.hpp>
#include <mcp/transport/transport.hpp>

#include <boost/asio/any_io_executor.hpp>
#include <chrono>
#include <functional>
#include <map>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace mcp {

/**
 * @brief Structured error returned by an MCP peer or generated by the client runtime.
 *
 * Unlike a plain std::runtime_error, this preserves the JSON-RPC error code and optional
 * data payload so callers can make protocol-aware decisions.
 */
class MCP_API McpError : public std::runtime_error {
   public:
    /** @brief Construct from a protocol error object. */
    explicit McpError(Error error);

    /**
     * @brief Construct a protocol-aware error.
     * @param code JSON-RPC or SDK-defined error code.
     * @param message Human-readable error message.
     * @param data Optional structured error details.
     */
    McpError(int code, std::string message, std::optional<nlohmann::json> data = std::nullopt);

    /** @brief Return the JSON-RPC or SDK-defined error code. */
    [[nodiscard]] int code() const noexcept { return error_.code; }
    /** @brief Return the protocol error message. */
    [[nodiscard]] const std::string& message() const noexcept { return error_.message; }
    /** @brief Return optional structured error details. */
    [[nodiscard]] const std::optional<nlohmann::json>& data() const noexcept { return error_.data; }
    /** @brief Return the complete protocol error object. */
    [[nodiscard]] const Error& error() const noexcept { return error_; }

   private:
    Error error_;
};

/** @brief Client-wide runtime behavior. */
struct ClientOptions {
    /** @brief Default time limit for outgoing requests. */
    std::chrono::milliseconds request_timeout{std::chrono::seconds(30)};
    /** @brief Reject malformed JSON-RPC envelopes received from the peer. */
    bool strict_protocol_validation{true};
};

/** @brief Overrides for one outgoing request. */
struct RequestOptions {
    /**
     * @brief Per-request deadline; uses ClientOptions::request_timeout when absent.
     *
     * A write still queued at the deadline is canceled before transmission. If
     * transport I/O has already started, remote execution may be ambiguous even
     * though the caller receives a timeout, as with any network request deadline.
     */
    std::optional<std::chrono::milliseconds> timeout;
};

/**
 * @brief MCP client that communicates with a server over a transport.
 *
 * @details Manages the JSON-RPC request/response lifecycle, including
 * an asynchronous read loop that dispatches incoming responses to their
 * corresponding pending requests. The client initiates the MCP handshake
 * via connect(), which sends an initialize request followed by an
 * initialized notification.
 *
 * Runtime I/O and request state are serialized on a boost::asio::strand.
 */
class MCP_API Client {
   public:
    /**
     * @brief Construct a Client.
     *
     * @param transport The transport to use for message exchange.
     *                  Ownership is shared with the client.
     * @param executor  The executor to use for async operations.
     * @param options   Default timeout and protocol-validation behavior.
     */
    Client(std::shared_ptr<ITransport> transport, const boost::asio::any_io_executor& executor,
           ClientOptions options = {});

    /// @brief Destructor. Closes the transport and clears pending requests
    /// so that asio-tied objects (timers, streams) are destroyed while the
    /// io_context is still alive.
    ~Client();

    Client(const Client&) = delete;
    Client& operator=(const Client&) = delete;
    Client(Client&&) = delete;
    Client& operator=(Client&&) = delete;

    /**
     * @brief Perform the MCP initialization handshake with default capabilities.
     * @param name Client implementation name.
     * @param version Client implementation version.
     * @return A task that resolves to the server's InitializeResult.
     */
    // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
    Task<InitializeResult> connect(std::string_view name, std::string_view version);

    /**
     * @brief Perform the MCP initialization handshake.
     *
     * @details Starts the read loop, sends initialize, waits for the server
     * response, and then sends notifications/initialized.
     *
     * @param client_info Information about this client implementation.
     * @param capabilities Capabilities supported by this client.
     * @return A task that resolves to the server's InitializeResult.
     */
    Task<InitializeResult> connect(const Implementation& client_info,
                                   const ClientCapabilities& capabilities);

    /**
     * @brief Send a JSON-RPC request and await its response.
     *
     * @details Assigns a unique integer ID, serializes the request on the stack,
     * and delegates to a coroutine that handles transport and suspension.
     * This is done to avoid GCC 11 SSO bugs and dangling references.
     *
     * @param method JSON-RPC method name.
     * @param params Optional parameters for the request.
     * @return A task that resolves to the result JSON object.
     * @throws McpError If the peer returns an error response or the request times out.
     */
    // [gcc11-sso: string_view]
    Task<nlohmann::json> send_request(std::string_view method,
                                      const std::optional<nlohmann::json>& params);

    /**
     * @brief Send a JSON-RPC request with per-request runtime options.
     */
    Task<nlohmann::json> send_request(std::string_view method,
                                      const std::optional<nlohmann::json>& params,
                                      const RequestOptions& request_options);

    /**
     * @brief Send a JSON-RPC notification (no response expected).
     *
     * @param method The notification method name.
     * @param params Optional parameters for the notification.
     * @return A task that completes when the notification has been written to the transport.
     */
    // [gcc11-sso: string_view]
    Task<void> send_notification(std::string_view method, const std::optional<nlohmann::json>& params);

    /**
     * @brief Get the number of pending (in-flight) requests.
     *
     * @return The count of requests awaiting responses.
     */
    [[nodiscard]] std::size_t pending_request_count() const;

    /// @brief Close the client, stopping the read loop and releasing resources.
    void close();

    /**
     * @brief Call a tool on the server.
     *
     * @details Serializes the arguments to JSON, sends a "tools/call"
     * request, and deserializes the response into a CallToolResult.
     *
     * @tparam Args A JsonSerializable type for the tool arguments.
     * @param name The name of the tool to call.
     * @param arguments The arguments to pass to the tool.
     * @return A task that resolves to the server's CallToolResult.
     */
    template <JsonSerializable Args>
    Task<CallToolResult> call_tool(const std::string& name, const Args& arguments) {
        // [gcc11-sso: not-a-coroutine]
        CallToolParams call_params;
        call_params.name = name;
        call_params.arguments = nlohmann::json(arguments);
        return call_and_parse<CallToolResult>("tools/call", nlohmann::json(std::move(call_params)));
    }

    /**
     * @brief List available tools from the server.
     *
     * @param cursor Optional pagination cursor.
     * @return A task that resolves to the server's ListToolsResult.
     */
    Task<ListToolsResult> list_tools(const std::optional<std::string>& cursor = std::nullopt);

    /**
     * @brief List available resources from the server.
     *
     * @param cursor Optional pagination cursor.
     * @return A task that resolves to the server's ListResourcesResult.
     */
    Task<ListResourcesResult> list_resources(const std::optional<std::string>& cursor = std::nullopt);

    /**
     * @brief Read a resource from the server by URI.
     *
     * @param uri The URI of the resource to read.
     * @return A task that resolves to the server's ReadResourceResult.
     */
    Task<ReadResourceResult> read_resource(const std::string& uri);

    /**
     * @brief List available resource templates from the server.
     *
     * @param cursor Optional pagination cursor.
     * @return A task that resolves to the server's ListResourceTemplatesResult.
     */
    Task<ListResourceTemplatesResult> list_resource_templates(
        const std::optional<std::string>& cursor = std::nullopt);

    /**
     * @brief List available prompts from the server.
     *
     * @param cursor Optional pagination cursor.
     * @return A task that resolves to the server's ListPromptsResult.
     */
    Task<ListPromptsResult> list_prompts(const std::optional<std::string>& cursor = std::nullopt);

    /**
     * @brief Get a specific prompt from the server.
     *
     * @param name The name of the prompt.
     * @param arguments Optional arguments to template the prompt.
     * @return A task that resolves to the server's GetPromptResult.
     */
    Task<GetPromptResult> get_prompt(
        const std::string& name,
        const std::optional<std::map<std::string, std::string>>& arguments = std::nullopt);

    /**
     * @brief Request completions from the server.
     *
     * @param params The completion parameters.
     * @return A task that resolves to the server's CompleteResult.
     */
    Task<CompleteResult> complete(const CompleteParams& params);

    /**
     * @brief Send a ping request to the connected server.
     *
     * @return A task that completes once the ping round-trip succeeds.
     */
    Task<void> ping();

    /**
     * @brief Send a cancellation notification for an in-flight request.
     *
     * @param request_id The ID of the request to cancel.
     * @param reason Optional human-readable reason for the cancellation.
     * @return A task that completes when the cancellation notification has been sent.
     */
    Task<void> cancel(const RequestId& request_id,
                      const std::optional<std::string>& reason = std::nullopt);

    /// @brief Type for notification callback: receives the notification params JSON.
    using NotificationCallback = std::function<void(const nlohmann::json&)>;

    /// @brief Type for request handler: receives params JSON, returns result JSON.
    using RequestHandler = std::function<Task<nlohmann::json>(const nlohmann::json&)>;

    /**
     * @brief Register a callback for incoming notifications from the server.
     *
     * @details When the server sends a notification with the given method,
     * the callback is invoked with the notification's params JSON.
     *
     * @param method The notification method to listen for (e.g. "notifications/progress").
     * @param callback The callback to invoke when the notification arrives.
     */
    void on_notification(const std::string& method, NotificationCallback callback);

    /// @brief Callback invoked for a deserialized progress notification.
    using ProgressCallback = std::function<void(const ProgressNotificationParams&)>;

    /**
     * @brief Register a callback for progress notifications.
     *
     * @param callback The callback invoked when a notifications/progress message arrives.
     */
    void on_progress(ProgressCallback callback);

    /**
     * @brief Register a handler for incoming requests from the server (reverse RPC).
     *
     * @details When the server sends a request with the given method (e.g. "ping",
     * "sampling/createMessage", "elicitation/create", "roots/list"), the handler
     * is invoked and its return value is sent back as the JSON-RPC response.
     *
     * @param method The request method to handle.
     * @param handler The async handler that returns a result JSON.
     */
    void on_request(const std::string& method, RequestHandler handler);

    /**
     * @brief Register a handler for incoming elicitation requests from the server.
     *
     * @details Convenience wrapper that registers a request handler for "elicitation/create".
     * The handler receives ElicitRequestParams and returns ElicitResult.
     *
     * @param handler Async handler: receives ElicitRequestParams, returns ElicitResult.
     */
    void on_elicitation(std::function<Task<ElicitResult>(const ElicitRequestParams&)> handler);

    /**
     * @brief Set static roots and auto-register the roots/list handler.
     *
     * @details Stores the given roots and registers a request handler for
     * "roots/list" that returns them. If notify is true, sends a
     * notifications/roots/list_changed notification to inform the server.
     *
     * @param roots The list of roots to provide.
     * @param notify Whether to send a roots-changed notification.
     */
    void set_roots(const std::vector<Root>& roots, bool notify = false);

    /**
     * @brief Register a dynamic handler for roots/list requests.
     *
     * @param handler Async handler that returns a ListRootsResult.
     */
    void on_roots_list(std::function<Task<ListRootsResult>(const nlohmann::json&)> handler);

   private:
    // [gcc11-sso: string_view] nlohmann::json is heap-allocated; string_view is trivially copyable.
    template <typename Result>
    Task<Result> call_and_parse(std::string_view method, std::optional<nlohmann::json> params) {
        return parse_result<Result>(send_request(method, params));
    }

    template <typename Result>
    static Task<Result> parse_result(Task<nlohmann::json> request) {
        auto result_json = co_await std::move(request);
        co_return result_json.template get<Result>();
    }

    struct Impl;
    std::shared_ptr<Impl> impl_;
};

}  // namespace mcp
