if(NOT DEFINED MCP_CPP_SDK_CONFIG_VERSION_TEMPLATE)
  message(FATAL_ERROR "config-version prerelease test is missing its template")
endif()

set(REMOVE_CONFIG_VERSION_TEST_OUTPUT FALSE)
if(NOT DEFINED MCP_CPP_SDK_CONFIG_VERSION_TEST_OUTPUT_DIR)
  if(NOT "$ENV{TMPDIR}" STREQUAL "")
    set(CONFIG_VERSION_TEST_TEMP_ROOT "$ENV{TMPDIR}")
  elseif(NOT "$ENV{TEMP}" STREQUAL "")
    set(CONFIG_VERSION_TEST_TEMP_ROOT "$ENV{TEMP}")
  elseif(WIN32)
    set(CONFIG_VERSION_TEST_TEMP_ROOT "$ENV{SystemDrive}/Temp")
  else()
    set(CONFIG_VERSION_TEST_TEMP_ROOT "/tmp")
  endif()
  string(
    RANDOM
    LENGTH 20
    ALPHABET 0123456789abcdef CONFIG_VERSION_TEST_SUFFIX)
  string(CONCAT CONFIG_VERSION_TEST_NAME "mcp-cpp-sdk-config-version-"
                "${CONFIG_VERSION_TEST_SUFFIX}")
  set(MCP_CPP_SDK_CONFIG_VERSION_TEST_OUTPUT_DIR
      "${CONFIG_VERSION_TEST_TEMP_ROOT}/${CONFIG_VERSION_TEST_NAME}")
  set(REMOVE_CONFIG_VERSION_TEST_OUTPUT TRUE)
endif()
file(MAKE_DIRECTORY "${MCP_CPP_SDK_CONFIG_VERSION_TEST_OUTPUT_DIR}")

set(MCP_CPP_SDK_VERSION_FULL "0.2.0-rc.1")
set(MCP_CPP_SDK_VERSION_PRERELEASE "-rc.1")
set(MCP_CPP_SDK_VERSION_MAJOR 0)
set(MCP_CPP_SDK_VERSION_MINOR 2)
set(MCP_CPP_SDK_VERSION_CORE "0.2.0")
set(CONFIG_VERSION_FILE
    "${MCP_CPP_SDK_CONFIG_VERSION_TEST_OUTPUT_DIR}/config-version-rc.cmake")
configure_file("${MCP_CPP_SDK_CONFIG_VERSION_TEMPLATE}"
               "${CONFIG_VERSION_FILE}" @ONLY)

foreach(expectation IN ITEMS "0.2.0-rc.1|TRUE|TRUE" "0.2.0|FALSE|FALSE"
                             "0.2.0-rc.2|FALSE|FALSE")
  string(REPLACE "|" ";" expectation_values "${expectation}")
  list(GET expectation_values 0 REQUESTED)
  list(GET expectation_values 1 EXPECTED_COMPATIBLE)
  list(GET expectation_values 2 EXPECTED_EXACT)
  unset(PACKAGE_VERSION)
  unset(PACKAGE_VERSION_COMPATIBLE)
  unset(PACKAGE_VERSION_EXACT)
  unset(PACKAGE_FIND_VERSION_RANGE)
  set(PACKAGE_FIND_VERSION "${REQUESTED}")
  include("${CONFIG_VERSION_FILE}")

  if(NOT PACKAGE_VERSION_COMPATIBLE STREQUAL "${EXPECTED_COMPATIBLE}")
    message(
      FATAL_ERROR
        "expected compatibility ${EXPECTED_COMPATIBLE} for ${REQUESTED}, got\n"
        "${PACKAGE_VERSION_COMPATIBLE}")
  endif()
  if(NOT PACKAGE_VERSION_EXACT STREQUAL "${EXPECTED_EXACT}")
    message(
      FATAL_ERROR "expected exactness ${EXPECTED_EXACT} for ${REQUESTED}, got\n"
                  "${PACKAGE_VERSION_EXACT}")
  endif()
endforeach()

if(REMOVE_CONFIG_VERSION_TEST_OUTPUT)
  file(REMOVE_RECURSE "${MCP_CPP_SDK_CONFIG_VERSION_TEST_OUTPUT_DIR}")
endif()
