// Generated by scripts/gen_json_matrix.py from scripts/json_census.py.
// Do not edit by hand: regenerate with `python3 scripts/gen_json_matrix.py`.
//
// Every peer-deserialisable protocol type, every field, four modes: the key
// absent, the key present and explicitly null, the key holding the wrong JSON
// type, and the key holding an oversized value of the right type.
//
// Each case asserts what the census predicts, so a disagreement between the
// code and the census fails here rather than in a user's session. Serialising
// an absent optional as an explicit null is the default for Go's
// encoding/json without omitempty and for a naively dumped Python dataclass,
// which puts the null column within reach of a careless peer rather than only
// a hostile one.
//
// scripts/check_json_matrix.py runs as a build step and fails when a protocol
// type has a from_json but is neither in this matrix nor excluded on the
// record, so the matrix cannot quietly fall behind the protocol.

#include <gtest/gtest.h>

#include <nlohmann/json.hpp>

#include <mcp/protocol/protocol.hpp>

#include <string>

namespace {

using nlohmann::json;

// How to pick a value a field does not accept. A variant of string and integer
// needs an object: "the other scalar type" is still something it accepts.
enum WrongHint {
    kWrongFromValue = 0,
    kWrongForceObject = 1
};

json wrong_typed(const json& value, int hint) {
    if (hint == kWrongForceObject) {
        return json{{"neither", "a string nor an integer"}};
    }
    if (value.is_boolean()) {
        return "not-a-bool";
    }
    if (value.is_number()) {
        return "not-a-number";
    }
    if (value.is_string()) {
        return 12345;
    }
    if (value.is_array()) {
        return json{{"not", "an array"}};
    }
    return json::array({"not an object"});
}

// A very large value that still has the type the field accepts. An oversized
// array stays an array *of its own element type*: filling it with strings
// would make it a wrong-type case wearing an oversized label, and the throw
// would then be read as a size limit that does not exist.
json oversized(const json& value) {
    if (value.is_boolean()) {
        return value;
    }
    if (value.is_number()) {
        return json(1000000000000000000LL);
    }
    if (value.is_string()) {
        return std::string(65536, 'A');
    }
    if (value.is_array()) {
        if (value.empty()) {
            return value;
        }
        json grown = json::array();
        for (int i = 0; i < 512; ++i) {
            grown.push_back(value.front());
        }
        return grown;
    }
    // An object grows by keys the serialiser ignores, so its shape is intact.
    json grown = value.is_object() ? value : json::object();
    for (int i = 0; i < 256; ++i) {
        grown["_pad" + std::to_string(i)] = std::string(256, 'A');
    }
    return grown;
}

// Parses `doc` into T and reports whether that threw.
template <typename T>
bool throws_on(const json& doc) {
    try {
        static_cast<void>(doc.get<T>());
        return false;
    } catch (const std::exception&) {
        return true;
    }
}

struct FieldExpect {
    const char* key;
    const char* present;  // a value the field accepts, as JSON text
    int wrong_hint;
    bool absent_throws;
    bool null_throws;
    bool wrong_throws;
    bool oversized_throws;
};

// Applies all four modes to one field and checks each against the census.
template <typename T>
void check_field(const json& baseline, const FieldExpect& f) {
    const json present = json::parse(f.present);

    json absent = baseline;
    absent.erase(f.key);
    {
        SCOPED_TRACE("absent");
        EXPECT_EQ(throws_on<T>(absent), f.absent_throws);
    }
    json with_null = baseline;
    with_null[f.key] = nullptr;
    {
        SCOPED_TRACE("null");
        EXPECT_EQ(throws_on<T>(with_null), f.null_throws);
    }
    json with_wrong = baseline;
    with_wrong[f.key] = wrong_typed(present, f.wrong_hint);
    {
        SCOPED_TRACE("wrong_type");
        EXPECT_EQ(throws_on<T>(with_wrong), f.wrong_throws);
    }
    json with_big = baseline;
    with_big[f.key] = oversized(present);
    {
        SCOPED_TRACE("oversized");
        EXPECT_EQ(throws_on<T>(with_big), f.oversized_throws);
    }
}

}  // namespace

TEST(JsonPeerInputMatrix, Annotations) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"audience", R"json(["user"])json", 0, false, true, true, false},
        {"lastModified", R"json("x")json", 0, false, true, true, false},
        {"priority", R"json(1.0)json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("Annotations.") + f.key);
        check_field<mcp::Annotations>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, AudioContent) {
    const json baseline = json::parse(R"json({"type":"audio","data":"x","mimeType":"x"})json");
    static const FieldExpect fields[] = {
        {"data", R"json("x")json", 0, true, true, true, false},
        {"mimeType", R"json("x")json", 0, true, true, true, false},
        {"type", R"json("audio")json", 0, true, true, true, true},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("AudioContent.") + f.key);
        check_field<mcp::AudioContent>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, BlobResourceContents) {
    const json baseline = json::parse(R"json({"uri":"x","blob":"x"})json");
    static const FieldExpect fields[] = {
        {"blob", R"json("x")json", 0, true, true, true, false},
        {"mimeType", R"json("x")json", 0, false, true, true, false},
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("BlobResourceContents.") + f.key);
        check_field<mcp::BlobResourceContents>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CallToolParams) {
    const json baseline = json::parse(R"json({"name":"x"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"name", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CallToolParams.") + f.key);
        check_field<mcp::CallToolParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CallToolRequest) {
    const json baseline = json::parse(R"json({"method":"tools/call","params":{"name":"x"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("tools/call")json", 0, true, true, true, false},
        {"params", R"json({"name":"x"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CallToolRequest.") + f.key);
        check_field<mcp::CallToolRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CallToolResult) {
    const json baseline = json::parse(R"json({"content":[]})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"content", R"json([])json", 0, true, true, true, false},
        {"isError", R"json(true)json", 0, false, true, true, false},
        {"structuredContent", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CallToolResult.") + f.key);
        check_field<mcp::CallToolResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CancelTaskRequest) {
    const json baseline = json::parse(R"json({"method":"tasks/cancel","params":{"id":"x"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("tasks/cancel")json", 0, true, true, true, false},
        {"params", R"json({"id":"x"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CancelTaskRequest.") + f.key);
        check_field<mcp::CancelTaskRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CancelTaskRequestParams) {
    const json baseline = json::parse(R"json({"id":"x"})json");
    static const FieldExpect fields[] = {
        {"id", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CancelTaskRequestParams.") + f.key);
        check_field<mcp::CancelTaskRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CancelTaskResult) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CancelTaskResult.") + f.key);
        check_field<mcp::CancelTaskResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CancelledNotification) {
    const json baseline =
        json::parse(R"json({"method":"notifications/cancelled","params":{"requestId":1}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/cancelled")json", 0, true, true, true, false},
        {"params", R"json({"requestId":1})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CancelledNotification.") + f.key);
        check_field<mcp::CancelledNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CancelledNotificationParams) {
    const json baseline = json::parse(R"json({"requestId":1})json");
    static const FieldExpect fields[] = {
        {"reason", R"json("x")json", 0, false, true, true, false},
        {"requestId", R"json(1)json", 1, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CancelledNotificationParams.") + f.key);
        check_field<mcp::CancelledNotificationParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ClientCapabilities) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"experimental", R"json({})json", 0, false, false, false, false},
        {"extensions", R"json({})json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ClientCapabilities.") + f.key);
        check_field<mcp::ClientCapabilities>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ClientCapabilities_ElicitationCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"form", R"json({})json", 0, false, false, false, false},
        {"url", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ClientCapabilities::ElicitationCapability.") + f.key);
        check_field<mcp::ClientCapabilities::ElicitationCapability>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ClientCapabilities_RootsCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"listChanged", R"json(true)json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ClientCapabilities::RootsCapability.") + f.key);
        check_field<mcp::ClientCapabilities::RootsCapability>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ClientCapabilities_SamplingCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"context", R"json({})json", 0, false, false, false, false},
        {"tools", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ClientCapabilities::SamplingCapability.") + f.key);
        check_field<mcp::ClientCapabilities::SamplingCapability>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ClientCapabilities_TaskRequestsCapability_ElicitationTaskCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"create", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(
            std::string("ClientCapabilities::TaskRequestsCapability::ElicitationTaskCapability.") +
            f.key);
        check_field<mcp::ClientCapabilities::TaskRequestsCapability::ElicitationTaskCapability>(
            baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ClientCapabilities_TaskRequestsCapability_SamplingTaskCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"createMessage", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(
            std::string("ClientCapabilities::TaskRequestsCapability::SamplingTaskCapability.") + f.key);
        check_field<mcp::ClientCapabilities::TaskRequestsCapability::SamplingTaskCapability>(baseline,
                                                                                             f);
    }
}

TEST(JsonPeerInputMatrix, ClientCapabilities_TasksCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"cancel", R"json({})json", 0, false, false, false, false},
        {"list", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ClientCapabilities::TasksCapability.") + f.key);
        check_field<mcp::ClientCapabilities::TasksCapability>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CompleteContext) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"arguments", R"json({})json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CompleteContext.") + f.key);
        check_field<mcp::CompleteContext>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CompleteParamsArgument) {
    const json baseline = json::parse(R"json({"name":"x","value":"x"})json");
    static const FieldExpect fields[] = {
        {"name", R"json("x")json", 0, true, true, true, false},
        {"value", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CompleteParamsArgument.") + f.key);
        check_field<mcp::CompleteParamsArgument>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CompleteResult) {
    const json baseline = json::parse(R"json({"completion":{"values":["x"]}})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"completion", R"json({"values":["x"]})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CompleteResult.") + f.key);
        check_field<mcp::CompleteResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CompletionResultDetails) {
    const json baseline = json::parse(R"json({"values":["x"]})json");
    static const FieldExpect fields[] = {
        {"hasMore", R"json(true)json", 0, false, true, true, false},
        {"total", R"json(1)json", 0, false, true, true, false},
        {"values", R"json(["x"])json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CompletionResultDetails.") + f.key);
        check_field<mcp::CompletionResultDetails>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CreateMessageRequest) {
    const json baseline = json::parse(
        R"json({"method":"sampling/createMessage","params":{"messages":[],"maxTokens":1}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("sampling/createMessage")json", 0, true, true, true, false},
        {"params", R"json({"messages":[],"maxTokens":1})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CreateMessageRequest.") + f.key);
        check_field<mcp::CreateMessageRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CreateMessageRequestParams) {
    const json baseline = json::parse(R"json({"messages":[],"maxTokens":1})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"includeContext", R"json("x")json", 0, false, true, true, false},
        {"maxTokens", R"json(1)json", 0, true, true, true, false},
        {"messages", R"json([])json", 0, true, true, true, false},
        {"metadata", R"json({})json", 0, false, false, false, false},
        {"modelPreferences", R"json({})json", 0, false, false, false, false},
        {"stopSequences", R"json(["x"])json", 0, false, true, true, false},
        {"systemPrompt", R"json("x")json", 0, false, true, true, false},
        {"temperature", R"json(1.0)json", 0, false, true, true, false},
        {"toolChoice", R"json({})json", 0, false, false, false, false},
        {"tools", R"json([{"name":"x","inputSchema":{}}])json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CreateMessageRequestParams.") + f.key);
        check_field<mcp::CreateMessageRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, CreateTaskResult) {
    const json baseline = json::parse(
        R"json({"task":{"taskId":"x","status":"cancelled","createdAt":"x","lastUpdatedAt":"x","ttl":1}})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"task",
         R"json({"taskId":"x","status":"cancelled","createdAt":"x","lastUpdatedAt":"x","ttl":1})json",
         0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("CreateTaskResult.") + f.key);
        check_field<mcp::CreateTaskResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, DiscoverRequest) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("DiscoverRequest.") + f.key);
        check_field<mcp::DiscoverRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, DiscoverResult) {
    const json baseline =
        json::parse(R"json({"resultType":"complete","supportedVersions":["x"],"capabilities":{}})json");
    static const FieldExpect fields[] = {
        {"cacheScope", R"json("public")json", 0, false, false, false, false},
        {"capabilities", R"json({})json", 0, true, false, false, false},
        {"instructions", R"json("x")json", 0, false, true, true, false},
        {"resultType", R"json("complete")json", 0, true, true, true, false},
        {"supportedVersions", R"json(["x"])json", 0, true, true, true, false},
        {"ttlMs", R"json(1)json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("DiscoverResult.") + f.key);
        check_field<mcp::DiscoverResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ElicitRequestFormParams) {
    const json baseline = json::parse(R"json({"mode":"form","message":"x","requestedSchema":{}})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"message", R"json("x")json", 0, true, true, true, false},
        {"mode", R"json("form")json", 0, true, true, true, false},
        {"requestedSchema", R"json({})json", 0, true, false, false, false},
        {"task", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ElicitRequestFormParams.") + f.key);
        check_field<mcp::ElicitRequestFormParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ElicitRequestURLParams) {
    const json baseline =
        json::parse(R"json({"mode":"url","message":"x","url":"x","elicitationId":"x"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"elicitationId", R"json("x")json", 0, true, true, true, false},
        {"message", R"json("x")json", 0, true, true, true, false},
        {"mode", R"json("url")json", 0, true, true, true, false},
        {"task", R"json({})json", 0, false, false, false, false},
        {"url", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ElicitRequestURLParams.") + f.key);
        check_field<mcp::ElicitRequestURLParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ElicitResult) {
    const json baseline = json::parse(R"json({"action":"accept"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"action", R"json("accept")json", 0, true, false, false, false},
        {"content", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ElicitResult.") + f.key);
        check_field<mcp::ElicitResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ElicitationCompleteNotification) {
    const json baseline = json::parse(
        R"json({"method":"notifications/elicitation/complete","params":{"requestId":1}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/elicitation/complete")json", 0, true, true, true, false},
        {"params", R"json({"requestId":1})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ElicitationCompleteNotification.") + f.key);
        check_field<mcp::ElicitationCompleteNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ElicitationCompleteNotificationParams) {
    const json baseline = json::parse(R"json({"requestId":1})json");
    static const FieldExpect fields[] = {
        {"requestId", R"json(1)json", 1, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ElicitationCompleteNotificationParams.") + f.key);
        check_field<mcp::ElicitationCompleteNotificationParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, EnumSchema) {
    const json baseline = json::parse(R"json({"type":"x"})json");
    static const FieldExpect fields[] = {
        {"description", R"json("x")json", 0, false, true, true, false},
        {"enum", R"json(["x"])json", 0, false, true, true, false},
        {"title", R"json("x")json", 0, false, true, true, false},
        {"type", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("EnumSchema.") + f.key);
        check_field<mcp::EnumSchema>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, Error) {
    const json baseline = json::parse(R"json({"code":1,"message":"x"})json");
    static const FieldExpect fields[] = {
        {"code", R"json(1)json", 0, true, true, true, false},
        {"data", R"json({})json", 0, false, false, false, false},
        {"message", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("Error.") + f.key);
        check_field<mcp::Error>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, GetPromptRequest) {
    const json baseline = json::parse(R"json({"method":"prompts/get","params":{"name":"x"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("prompts/get")json", 0, true, true, true, false},
        {"params", R"json({"name":"x"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("GetPromptRequest.") + f.key);
        check_field<mcp::GetPromptRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, GetPromptRequestParams) {
    const json baseline = json::parse(R"json({"name":"x"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"arguments", R"json({})json", 0, false, true, true, false},
        {"name", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("GetPromptRequestParams.") + f.key);
        check_field<mcp::GetPromptRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, GetPromptResult) {
    const json baseline = json::parse(R"json({"messages":[]})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"description", R"json("x")json", 0, false, true, true, false},
        {"messages", R"json([])json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("GetPromptResult.") + f.key);
        check_field<mcp::GetPromptResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, GetTaskPayloadRequest) {
    const json baseline = json::parse(R"json({"method":"tasks/getPayload","params":{"id":"x"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("tasks/getPayload")json", 0, true, true, true, false},
        {"params", R"json({"id":"x"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("GetTaskPayloadRequest.") + f.key);
        check_field<mcp::GetTaskPayloadRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, GetTaskPayloadRequestParams) {
    const json baseline = json::parse(R"json({"id":"x"})json");
    static const FieldExpect fields[] = {
        {"id", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("GetTaskPayloadRequestParams.") + f.key);
        check_field<mcp::GetTaskPayloadRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, GetTaskPayloadResult) {
    const json baseline = json::parse(R"json({"payload":{}})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"payload", R"json({})json", 0, true, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("GetTaskPayloadResult.") + f.key);
        check_field<mcp::GetTaskPayloadResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, GetTaskRequest) {
    const json baseline = json::parse(R"json({"method":"tasks/get","params":{"id":"x"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("tasks/get")json", 0, true, true, true, false},
        {"params", R"json({"id":"x"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("GetTaskRequest.") + f.key);
        check_field<mcp::GetTaskRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, GetTaskRequestParams) {
    const json baseline = json::parse(R"json({"id":"x"})json");
    static const FieldExpect fields[] = {
        {"id", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("GetTaskRequestParams.") + f.key);
        check_field<mcp::GetTaskRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, GetTaskResult) {
    const json baseline = json::parse(
        R"json({"taskId":"x","status":"cancelled","createdAt":"x","lastUpdatedAt":"x","ttl":1})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"createdAt", R"json("x")json", 0, true, true, true, false},
        {"lastUpdatedAt", R"json("x")json", 0, true, true, true, false},
        {"pollInterval", R"json(1)json", 0, false, true, true, false},
        {"status", R"json("cancelled")json", 0, true, false, false, false},
        {"statusMessage", R"json("x")json", 0, false, true, true, false},
        {"taskId", R"json("x")json", 0, true, true, true, false},
        {"ttl", R"json(1)json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("GetTaskResult.") + f.key);
        check_field<mcp::GetTaskResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, Icon) {
    const json baseline = json::parse(R"json({"src":"x"})json");
    static const FieldExpect fields[] = {
        {"mimeType", R"json("x")json", 0, false, true, true, false},
        {"sizes", R"json(["x"])json", 0, false, true, true, false},
        {"src", R"json("x")json", 0, true, true, true, false},
        {"theme", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("Icon.") + f.key);
        check_field<mcp::Icon>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ImageContent) {
    const json baseline = json::parse(R"json({"type":"image","data":"x","mimeType":"x"})json");
    static const FieldExpect fields[] = {
        {"data", R"json("x")json", 0, true, true, true, false},
        {"mimeType", R"json("x")json", 0, true, true, true, false},
        {"type", R"json("image")json", 0, true, true, true, true},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ImageContent.") + f.key);
        check_field<mcp::ImageContent>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, Implementation) {
    const json baseline = json::parse(R"json({"name":"x","version":"x"})json");
    static const FieldExpect fields[] = {
        {"description", R"json("x")json", 0, false, true, true, false},
        {"icons", R"json([{"src":"x"}])json", 0, false, true, true, false},
        {"name", R"json("x")json", 0, true, true, true, false},
        {"title", R"json("x")json", 0, false, true, true, false},
        {"version", R"json("x")json", 0, true, true, true, false},
        {"websiteUrl", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("Implementation.") + f.key);
        check_field<mcp::Implementation>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, InitializedNotification) {
    const json baseline = json::parse(R"json({"method":"notifications/initialized"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/initialized")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("InitializedNotification.") + f.key);
        check_field<mcp::InitializedNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, JSONRPCErrorResponse) {
    const json baseline = json::parse(R"json({"error":{"code":1,"message":"x"},"jsonrpc":"2.0"})json");
    static const FieldExpect fields[] = {
        {"error", R"json({"code":1,"message":"x"})json", 0, true, true, true, false},
        {"id", R"json(1)json", 1, false, false, true, false},
        {"jsonrpc", R"json("2.0")json", 0, true, true, true, true},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("JSONRPCErrorResponse.") + f.key);
        check_field<mcp::JSONRPCErrorResponse>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, JSONRPCNotification) {
    const json baseline = json::parse(R"json({"jsonrpc":"2.0","method":"x"})json");
    static const FieldExpect fields[] = {
        {"jsonrpc", R"json("2.0")json", 0, true, true, true, true},
        {"method", R"json("x")json", 0, true, true, true, false},
        {"params", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("JSONRPCNotification.") + f.key);
        check_field<mcp::JSONRPCNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, JSONRPCRequest) {
    const json baseline = json::parse(R"json({"id":1,"jsonrpc":"2.0","method":"x"})json");
    static const FieldExpect fields[] = {
        {"id", R"json(1)json", 1, true, true, true, false},
        {"jsonrpc", R"json("2.0")json", 0, true, true, true, true},
        {"method", R"json("x")json", 0, true, true, true, false},
        {"params", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("JSONRPCRequest.") + f.key);
        check_field<mcp::JSONRPCRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, JSONRPCResultResponse) {
    const json baseline = json::parse(R"json({"id":1,"jsonrpc":"2.0","result":{}})json");
    static const FieldExpect fields[] = {
        {"id", R"json(1)json", 1, true, true, true, false},
        {"jsonrpc", R"json("2.0")json", 0, true, true, true, true},
        {"result", R"json({})json", 0, true, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("JSONRPCResultResponse.") + f.key);
        check_field<mcp::JSONRPCResultResponse>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListPromptsRequest) {
    const json baseline = json::parse(R"json({"method":"prompts/list"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("prompts/list")json", 0, true, true, true, false},
        {"params", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListPromptsRequest.") + f.key);
        check_field<mcp::ListPromptsRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListPromptsResult) {
    const json baseline = json::parse(R"json({"prompts":[{"name":"x"}]})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"nextCursor", R"json("x")json", 0, false, true, true, false},
        {"prompts", R"json([{"name":"x"}])json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListPromptsResult.") + f.key);
        check_field<mcp::ListPromptsResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListResourceTemplatesRequest) {
    const json baseline = json::parse(R"json({"method":"resources/templates/list"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("resources/templates/list")json", 0, true, true, true, false},
        {"params", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListResourceTemplatesRequest.") + f.key);
        check_field<mcp::ListResourceTemplatesRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListResourceTemplatesRequestParams) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"cursor", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListResourceTemplatesRequestParams.") + f.key);
        check_field<mcp::ListResourceTemplatesRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListResourceTemplatesResult) {
    const json baseline =
        json::parse(R"json({"resourceTemplates":[{"uriTemplate":"x","name":"x"}]})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"nextCursor", R"json("x")json", 0, false, true, true, false},
        {"resourceTemplates", R"json([{"uriTemplate":"x","name":"x"}])json", 0, true, true, true,
         false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListResourceTemplatesResult.") + f.key);
        check_field<mcp::ListResourceTemplatesResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListResourcesRequest) {
    const json baseline = json::parse(R"json({"method":"resources/list"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("resources/list")json", 0, true, true, true, false},
        {"params", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListResourcesRequest.") + f.key);
        check_field<mcp::ListResourcesRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListResourcesRequestParams) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"cursor", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListResourcesRequestParams.") + f.key);
        check_field<mcp::ListResourcesRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListResourcesResult) {
    const json baseline = json::parse(R"json({"resources":[{"uri":"x","name":"x"}]})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"nextCursor", R"json("x")json", 0, false, true, true, false},
        {"resources", R"json([{"uri":"x","name":"x"}])json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListResourcesResult.") + f.key);
        check_field<mcp::ListResourcesResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListRootsRequest) {
    const json baseline = json::parse(R"json({"method":"roots/list"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("roots/list")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListRootsRequest.") + f.key);
        check_field<mcp::ListRootsRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListRootsResult) {
    const json baseline = json::parse(R"json({"roots":[{"uri":"x"}]})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"roots", R"json([{"uri":"x"}])json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListRootsResult.") + f.key);
        check_field<mcp::ListRootsResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListTasksRequest) {
    const json baseline = json::parse(R"json({"method":"tasks/list"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("tasks/list")json", 0, true, true, true, false},
        {"params", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListTasksRequest.") + f.key);
        check_field<mcp::ListTasksRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListTasksRequestParams) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"cursor", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListTasksRequestParams.") + f.key);
        check_field<mcp::ListTasksRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListTasksResult) {
    const json baseline = json::parse(
        R"json({"tasks":[{"taskId":"x","status":"cancelled","createdAt":"x","lastUpdatedAt":"x","ttl":1}]})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"nextCursor", R"json("x")json", 0, false, true, true, false},
        {"tasks",
         R"json([{"taskId":"x","status":"cancelled","createdAt":"x","lastUpdatedAt":"x","ttl":1}])json",
         0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListTasksResult.") + f.key);
        check_field<mcp::ListTasksResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListToolsRequest) {
    const json baseline = json::parse(R"json({"method":"tools/list"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("tools/list")json", 0, true, true, true, false},
        {"params", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListToolsRequest.") + f.key);
        check_field<mcp::ListToolsRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListToolsRequestParams) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"cursor", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListToolsRequestParams.") + f.key);
        check_field<mcp::ListToolsRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ListToolsResult) {
    const json baseline = json::parse(R"json({"tools":[{"name":"x","inputSchema":{}}]})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"nextCursor", R"json("x")json", 0, false, true, true, false},
        {"tools", R"json([{"name":"x","inputSchema":{}}])json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ListToolsResult.") + f.key);
        check_field<mcp::ListToolsResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, LoggingMessageNotification) {
    const json baseline = json::parse(
        R"json({"method":"notifications/message","params":{"level":"emergency","data":{}}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/message")json", 0, true, true, true, false},
        {"params", R"json({"level":"emergency","data":{}})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("LoggingMessageNotification.") + f.key);
        check_field<mcp::LoggingMessageNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, LoggingMessageNotificationParams) {
    const json baseline = json::parse(R"json({"level":"emergency","data":{}})json");
    static const FieldExpect fields[] = {
        {"data", R"json({})json", 0, true, false, false, false},
        {"level", R"json("emergency")json", 0, true, false, false, false},
        {"logger", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("LoggingMessageNotificationParams.") + f.key);
        check_field<mcp::LoggingMessageNotificationParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ModelHint) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"name", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ModelHint.") + f.key);
        check_field<mcp::ModelHint>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ModelPreferences) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"costPriority", R"json(1.0)json", 0, false, true, true, false},
        {"hints", R"json([{}])json", 0, false, true, true, false},
        {"intelligencePriority", R"json(1.0)json", 0, false, true, true, false},
        {"speedPriority", R"json(1.0)json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ModelPreferences.") + f.key);
        check_field<mcp::ModelPreferences>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, PaginatedRequestParams) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"cursor", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("PaginatedRequestParams.") + f.key);
        check_field<mcp::PaginatedRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, PingRequest) {
    const json baseline = json::parse(R"json({"method":"ping"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("ping")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("PingRequest.") + f.key);
        check_field<mcp::PingRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ProgressNotification) {
    const json baseline = json::parse(
        R"json({"method":"notifications/progress","params":{"progressToken":1,"progress":1.0}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/progress")json", 0, true, true, true, false},
        {"params", R"json({"progressToken":1,"progress":1.0})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ProgressNotification.") + f.key);
        check_field<mcp::ProgressNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ProgressNotificationParams) {
    const json baseline = json::parse(R"json({"progressToken":1,"progress":1.0})json");
    static const FieldExpect fields[] = {
        {"message", R"json("x")json", 0, false, true, true, false},
        {"progress", R"json(1.0)json", 0, true, true, true, false},
        {"progressToken", R"json(1)json", 1, true, true, true, false},
        {"total", R"json(1.0)json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ProgressNotificationParams.") + f.key);
        check_field<mcp::ProgressNotificationParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, Prompt) {
    const json baseline = json::parse(R"json({"name":"x"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"arguments", R"json([{"name":"x"}])json", 0, false, true, true, false},
        {"description", R"json("x")json", 0, false, true, true, false},
        {"icons", R"json([{"src":"x"}])json", 0, false, true, true, false},
        {"name", R"json("x")json", 0, true, true, true, false},
        {"title", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("Prompt.") + f.key);
        check_field<mcp::Prompt>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, PromptArgument) {
    const json baseline = json::parse(R"json({"name":"x"})json");
    static const FieldExpect fields[] = {
        {"description", R"json("x")json", 0, false, true, true, false},
        {"name", R"json("x")json", 0, true, true, true, false},
        {"required", R"json(true)json", 0, false, true, true, false},
        {"title", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("PromptArgument.") + f.key);
        check_field<mcp::PromptArgument>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, PromptListChangedNotification) {
    const json baseline = json::parse(R"json({"method":"notifications/prompts/list_changed"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/prompts/list_changed")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("PromptListChangedNotification.") + f.key);
        check_field<mcp::PromptListChangedNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, PromptReference) {
    const json baseline = json::parse(R"json({"name":"x","type":"ref/prompt"})json");
    static const FieldExpect fields[] = {
        {"name", R"json("x")json", 0, true, true, true, false},
        {"type", R"json("ref/prompt")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("PromptReference.") + f.key);
        check_field<mcp::PromptReference>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ReadResourceRequest) {
    const json baseline = json::parse(R"json({"method":"resources/read","params":{"uri":"x"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("resources/read")json", 0, true, true, true, false},
        {"params", R"json({"uri":"x"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ReadResourceRequest.") + f.key);
        check_field<mcp::ReadResourceRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ReadResourceRequestParams) {
    const json baseline = json::parse(R"json({"uri":"x"})json");
    static const FieldExpect fields[] = {
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ReadResourceRequestParams.") + f.key);
        check_field<mcp::ReadResourceRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ReadResourceResult) {
    const json baseline = json::parse(R"json({"contents":[]})json");
    static const FieldExpect fields[] = {
        {"contents", R"json([])json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ReadResourceResult.") + f.key);
        check_field<mcp::ReadResourceResult>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, RelatedTaskMetadata) {
    const json baseline = json::parse(R"json({"id":"x"})json");
    static const FieldExpect fields[] = {
        {"id", R"json("x")json", 0, true, true, true, false},
        {"title", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("RelatedTaskMetadata.") + f.key);
        check_field<mcp::RelatedTaskMetadata>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, Resource) {
    const json baseline = json::parse(R"json({"uri":"x","name":"x"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"annotations", R"json({})json", 0, false, false, false, false},
        {"description", R"json("x")json", 0, false, true, true, false},
        {"icons", R"json([{"src":"x"}])json", 0, false, true, true, false},
        {"mimeType", R"json("x")json", 0, false, true, true, false},
        {"name", R"json("x")json", 0, true, true, true, false},
        {"size", R"json(1)json", 0, false, true, true, false},
        {"title", R"json("x")json", 0, false, true, true, false},
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("Resource.") + f.key);
        check_field<mcp::Resource>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ResourceLink) {
    const json baseline = json::parse(R"json({"type":"resource_link","uri":"x","name":"x"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"annotations", R"json({})json", 0, false, false, false, false},
        {"description", R"json("x")json", 0, false, true, true, false},
        {"icons", R"json([{"src":"x"}])json", 0, false, true, true, false},
        {"mimeType", R"json("x")json", 0, false, true, true, false},
        {"name", R"json("x")json", 0, true, true, true, false},
        {"size", R"json(1)json", 0, false, true, true, false},
        {"title", R"json("x")json", 0, false, true, true, false},
        {"type", R"json("resource_link")json", 0, true, true, true, true},
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ResourceLink.") + f.key);
        check_field<mcp::ResourceLink>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ResourceListChangedNotification) {
    const json baseline = json::parse(R"json({"method":"notifications/resources/list_changed"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/resources/list_changed")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ResourceListChangedNotification.") + f.key);
        check_field<mcp::ResourceListChangedNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ResourceSubscribeParams) {
    const json baseline = json::parse(R"json({"uri":"x"})json");
    static const FieldExpect fields[] = {
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ResourceSubscribeParams.") + f.key);
        check_field<mcp::ResourceSubscribeParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ResourceTemplate) {
    const json baseline = json::parse(R"json({"uriTemplate":"x","name":"x"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"annotations", R"json({})json", 0, false, false, false, false},
        {"description", R"json("x")json", 0, false, true, true, false},
        {"icons", R"json([{"src":"x"}])json", 0, false, true, true, false},
        {"mimeType", R"json("x")json", 0, false, true, true, false},
        {"name", R"json("x")json", 0, true, true, true, false},
        {"title", R"json("x")json", 0, false, true, true, false},
        {"uriTemplate", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ResourceTemplate.") + f.key);
        check_field<mcp::ResourceTemplate>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ResourceTemplateReference) {
    const json baseline = json::parse(R"json({"type":"ref/resource","uri":"x"})json");
    static const FieldExpect fields[] = {
        {"type", R"json("ref/resource")json", 0, true, true, true, false},
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ResourceTemplateReference.") + f.key);
        check_field<mcp::ResourceTemplateReference>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ResourceUnsubscribeParams) {
    const json baseline = json::parse(R"json({"uri":"x"})json");
    static const FieldExpect fields[] = {
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ResourceUnsubscribeParams.") + f.key);
        check_field<mcp::ResourceUnsubscribeParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ResourceUpdatedNotification) {
    const json baseline =
        json::parse(R"json({"method":"notifications/resources/updated","params":{"uri":"x"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/resources/updated")json", 0, true, true, true, false},
        {"params", R"json({"uri":"x"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ResourceUpdatedNotification.") + f.key);
        check_field<mcp::ResourceUpdatedNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ResourceUpdatedNotificationParams) {
    const json baseline = json::parse(R"json({"uri":"x"})json");
    static const FieldExpect fields[] = {
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ResourceUpdatedNotificationParams.") + f.key);
        check_field<mcp::ResourceUpdatedNotificationParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, Root) {
    const json baseline = json::parse(R"json({"uri":"x"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"name", R"json("x")json", 0, false, true, true, false},
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("Root.") + f.key);
        check_field<mcp::Root>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, RootsListChangedNotification) {
    const json baseline = json::parse(R"json({"method":"notifications/roots/list_changed"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/roots/list_changed")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("RootsListChangedNotification.") + f.key);
        check_field<mcp::RootsListChangedNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ServerCapabilities) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"completions", R"json({})json", 0, false, false, false, false},
        {"experimental", R"json({})json", 0, false, false, false, false},
        {"extensions", R"json({})json", 0, false, true, true, false},
        {"logging", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ServerCapabilities.") + f.key);
        check_field<mcp::ServerCapabilities>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ServerCapabilities_PromptsCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"listChanged", R"json(true)json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ServerCapabilities::PromptsCapability.") + f.key);
        check_field<mcp::ServerCapabilities::PromptsCapability>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ServerCapabilities_ResourcesCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"listChanged", R"json(true)json", 0, false, true, true, false},
        {"subscribe", R"json(true)json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ServerCapabilities::ResourcesCapability.") + f.key);
        check_field<mcp::ServerCapabilities::ResourcesCapability>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ServerCapabilities_TaskRequestsCapability_ToolsTaskCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"call", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ServerCapabilities::TaskRequestsCapability::ToolsTaskCapability.") +
                     f.key);
        check_field<mcp::ServerCapabilities::TaskRequestsCapability::ToolsTaskCapability>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ServerCapabilities_TasksCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"cancel", R"json({})json", 0, false, false, false, false},
        {"list", R"json({})json", 0, false, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ServerCapabilities::TasksCapability.") + f.key);
        check_field<mcp::ServerCapabilities::TasksCapability>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ServerCapabilities_ToolsCapability) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"listChanged", R"json(true)json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ServerCapabilities::ToolsCapability.") + f.key);
        check_field<mcp::ServerCapabilities::ToolsCapability>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, SetLevelRequest) {
    const json baseline =
        json::parse(R"json({"method":"logging/setLevel","params":{"level":"emergency"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("logging/setLevel")json", 0, true, true, true, false},
        {"params", R"json({"level":"emergency"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("SetLevelRequest.") + f.key);
        check_field<mcp::SetLevelRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, SetLevelRequestParams) {
    const json baseline = json::parse(R"json({"level":"emergency"})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"level", R"json("emergency")json", 0, true, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("SetLevelRequestParams.") + f.key);
        check_field<mcp::SetLevelRequestParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, SubscribeRequest) {
    const json baseline =
        json::parse(R"json({"method":"resources/subscribe","params":{"uri":"x"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("resources/subscribe")json", 0, true, true, true, false},
        {"params", R"json({"uri":"x"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("SubscribeRequest.") + f.key);
        check_field<mcp::SubscribeRequest>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, TaskData) {
    const json baseline = json::parse(
        R"json({"taskId":"x","status":"cancelled","createdAt":"x","lastUpdatedAt":"x","ttl":1})json");
    static const FieldExpect fields[] = {
        {"createdAt", R"json("x")json", 0, true, true, true, false},
        {"lastUpdatedAt", R"json("x")json", 0, true, true, true, false},
        {"pollInterval", R"json(1)json", 0, false, true, true, false},
        {"status", R"json("cancelled")json", 0, true, false, false, false},
        {"statusMessage", R"json("x")json", 0, false, true, true, false},
        {"taskId", R"json("x")json", 0, true, true, true, false},
        {"ttl", R"json(1)json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("TaskData.") + f.key);
        check_field<mcp::TaskData>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, TaskMetadata) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"relatedTasks", R"json([{"id":"x"}])json", 0, false, true, true, false},
        {"ttl", R"json(1)json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("TaskMetadata.") + f.key);
        check_field<mcp::TaskMetadata>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, TaskStatusNotification) {
    const json baseline = json::parse(
        R"json({"method":"notifications/tasks/status","params":{"id":"x","status":"cancelled"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/tasks/status")json", 0, true, true, true, false},
        {"params", R"json({"id":"x","status":"cancelled"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("TaskStatusNotification.") + f.key);
        check_field<mcp::TaskStatusNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, TaskStatusNotificationParams) {
    const json baseline = json::parse(R"json({"id":"x","status":"cancelled"})json");
    static const FieldExpect fields[] = {
        {"id", R"json("x")json", 0, true, true, true, false},
        {"message", R"json("x")json", 0, false, true, true, false},
        {"metadata", R"json({})json", 0, false, false, false, false},
        {"status", R"json("cancelled")json", 0, true, false, false, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("TaskStatusNotificationParams.") + f.key);
        check_field<mcp::TaskStatusNotificationParams>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, TextContent) {
    const json baseline = json::parse(R"json({"type":"text","text":"x"})json");
    static const FieldExpect fields[] = {
        {"text", R"json("x")json", 0, true, true, true, false},
        {"type", R"json("text")json", 0, true, true, true, true},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("TextContent.") + f.key);
        check_field<mcp::TextContent>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, TextResourceContents) {
    const json baseline = json::parse(R"json({"uri":"x","text":"x"})json");
    static const FieldExpect fields[] = {
        {"mimeType", R"json("x")json", 0, false, true, true, false},
        {"text", R"json("x")json", 0, true, true, true, false},
        {"uri", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("TextResourceContents.") + f.key);
        check_field<mcp::TextResourceContents>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, Tool) {
    const json baseline = json::parse(R"json({"name":"x","inputSchema":{}})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"annotations", R"json({})json", 0, false, false, false, false},
        {"description", R"json("x")json", 0, false, true, true, false},
        {"execution", R"json({"taskSupport":"x"})json", 0, false, true, true, false},
        {"icons", R"json([{"src":"x"}])json", 0, false, true, true, false},
        {"inputSchema", R"json({})json", 0, true, false, false, false},
        {"name", R"json("x")json", 0, true, true, true, false},
        {"outputSchema", R"json({})json", 0, false, false, false, false},
        {"title", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("Tool.") + f.key);
        check_field<mcp::Tool>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ToolAnnotations) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"destructiveHint", R"json(true)json", 0, false, true, true, false},
        {"idempotentHint", R"json(true)json", 0, false, true, true, false},
        {"openWorldHint", R"json(true)json", 0, false, true, true, false},
        {"readOnlyHint", R"json(true)json", 0, false, true, true, false},
        {"title", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ToolAnnotations.") + f.key);
        check_field<mcp::ToolAnnotations>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ToolChoice) {
    const json baseline = json::parse(R"json({})json");
    static const FieldExpect fields[] = {
        {"mode", R"json("x")json", 0, false, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ToolChoice.") + f.key);
        check_field<mcp::ToolChoice>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ToolExecution) {
    const json baseline = json::parse(R"json({"taskSupport":"x"})json");
    static const FieldExpect fields[] = {
        {"taskSupport", R"json("x")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ToolExecution.") + f.key);
        check_field<mcp::ToolExecution>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ToolListChangedNotification) {
    const json baseline = json::parse(R"json({"method":"notifications/tools/list_changed"})json");
    static const FieldExpect fields[] = {
        {"method", R"json("notifications/tools/list_changed")json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ToolListChangedNotification.") + f.key);
        check_field<mcp::ToolListChangedNotification>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ToolResultContent) {
    const json baseline = json::parse(R"json({"type":"tool_result","toolUseId":"x","content":{}})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"content", R"json({})json", 0, true, false, false, false},
        {"isError", R"json(true)json", 0, false, true, true, false},
        {"structuredContent", R"json({})json", 0, false, false, false, false},
        {"toolUseId", R"json("x")json", 0, true, true, true, false},
        {"type", R"json("tool_result")json", 0, true, true, true, true},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ToolResultContent.") + f.key);
        check_field<mcp::ToolResultContent>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, ToolUseContent) {
    const json baseline = json::parse(R"json({"type":"tool_use","id":"x","name":"x","input":{}})json");
    static const FieldExpect fields[] = {
        {"_meta", R"json({})json", 0, false, false, false, false},
        {"id", R"json("x")json", 0, true, true, true, false},
        {"input", R"json({})json", 0, true, false, false, false},
        {"name", R"json("x")json", 0, true, true, true, false},
        {"type", R"json("tool_use")json", 0, true, true, true, true},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("ToolUseContent.") + f.key);
        check_field<mcp::ToolUseContent>(baseline, f);
    }
}

TEST(JsonPeerInputMatrix, UnsubscribeRequest) {
    const json baseline =
        json::parse(R"json({"method":"resources/unsubscribe","params":{"uri":"x"}})json");
    static const FieldExpect fields[] = {
        {"method", R"json("resources/unsubscribe")json", 0, true, true, true, false},
        {"params", R"json({"uri":"x"})json", 0, true, true, true, false},
    };
    for (const auto& f : fields) {
        SCOPED_TRACE(std::string("UnsubscribeRequest.") + f.key);
        check_field<mcp::UnsubscribeRequest>(baseline, f);
    }
}

// The matrix's own arithmetic.  `types x fields x modes` is what a generated
// suite is worth; a hand-written suite of the same size is only worth what its
// author thought to write down.
TEST(JsonPeerInputMatrix, CaseCountIsDerived) {
    constexpr int types = 117;
    constexpr int fields = 317;
    constexpr int modes = 4;
    constexpr int generated_cases = 1268;
    EXPECT_EQ(generated_cases, fields * modes);
    EXPECT_GT(types, 0);
}

// Types in the matrix (checked against the protocol headers at build time):
//   Annotations
//   AudioContent
//   BlobResourceContents
//   CallToolParams
//   CallToolRequest
//   CallToolResult
//   CancelTaskRequest
//   CancelTaskRequestParams
//   CancelTaskResult
//   CancelledNotification
//   CancelledNotificationParams
//   ClientCapabilities
//   ClientCapabilities::ElicitationCapability
//   ClientCapabilities::RootsCapability
//   ClientCapabilities::SamplingCapability
//   ClientCapabilities::TaskRequestsCapability::ElicitationTaskCapability
//   ClientCapabilities::TaskRequestsCapability::SamplingTaskCapability
//   ClientCapabilities::TasksCapability
//   CompleteContext
//   CompleteParamsArgument
//   CompleteResult
//   CompletionResultDetails
//   CreateMessageRequest
//   CreateMessageRequestParams
//   CreateTaskResult
//   DiscoverRequest
//   DiscoverResult
//   ElicitRequestFormParams
//   ElicitRequestURLParams
//   ElicitResult
//   ElicitationCompleteNotification
//   ElicitationCompleteNotificationParams
//   EnumSchema
//   Error
//   GetPromptRequest
//   GetPromptRequestParams
//   GetPromptResult
//   GetTaskPayloadRequest
//   GetTaskPayloadRequestParams
//   GetTaskPayloadResult
//   GetTaskRequest
//   GetTaskRequestParams
//   GetTaskResult
//   Icon
//   ImageContent
//   Implementation
//   InitializedNotification
//   JSONRPCErrorResponse
//   JSONRPCNotification
//   JSONRPCRequest
//   JSONRPCResultResponse
//   ListPromptsRequest
//   ListPromptsResult
//   ListResourceTemplatesRequest
//   ListResourceTemplatesRequestParams
//   ListResourceTemplatesResult
//   ListResourcesRequest
//   ListResourcesRequestParams
//   ListResourcesResult
//   ListRootsRequest
//   ListRootsResult
//   ListTasksRequest
//   ListTasksRequestParams
//   ListTasksResult
//   ListToolsRequest
//   ListToolsRequestParams
//   ListToolsResult
//   LoggingMessageNotification
//   LoggingMessageNotificationParams
//   ModelHint
//   ModelPreferences
//   PaginatedRequestParams
//   PingRequest
//   ProgressNotification
//   ProgressNotificationParams
//   Prompt
//   PromptArgument
//   PromptListChangedNotification
//   PromptReference
//   ReadResourceRequest
//   ReadResourceRequestParams
//   ReadResourceResult
//   RelatedTaskMetadata
//   Resource
//   ResourceLink
//   ResourceListChangedNotification
//   ResourceSubscribeParams
//   ResourceTemplate
//   ResourceTemplateReference
//   ResourceUnsubscribeParams
//   ResourceUpdatedNotification
//   ResourceUpdatedNotificationParams
//   Root
//   RootsListChangedNotification
//   ServerCapabilities
//   ServerCapabilities::PromptsCapability
//   ServerCapabilities::ResourcesCapability
//   ServerCapabilities::TaskRequestsCapability::ToolsTaskCapability
//   ServerCapabilities::TasksCapability
//   ServerCapabilities::ToolsCapability
//   SetLevelRequest
//   SetLevelRequestParams
//   SubscribeRequest
//   TaskData
//   TaskMetadata
//   TaskStatusNotification
//   TaskStatusNotificationParams
//   TextContent
//   TextResourceContents
//   Tool
//   ToolAnnotations
//   ToolChoice
//   ToolExecution
//   ToolListChangedNotification
//   ToolResultContent
//   ToolUseContent
//   UnsubscribeRequest
// Types deliberately not in the matrix, and why:
//   ClientCapabilities::TaskRequestsCapability: no census row governs any of its fields
//   CompleteParams: no baseline document could be synthesised
//   CompleteReference: std::variant; from_json dispatches on the 'type' discriminator
//   ContentBlock: std::variant; from_json dispatches on the 'type' discriminator
//   CreateMessageResult: no baseline document could be synthesised
//   ElicitRequest: no baseline document could be synthesised
//   ElicitRequestParams: std::variant; from_json dispatches on mode
//   EmbeddedResource: no baseline document could be synthesised
//   InitializeRequest: no baseline document could be synthesised
//   InitializeResult: no baseline document could be synthesised
//   JSONRPCMessage: std::variant; from_json dispatches on which key is present
//   JSONRPCResponse: std::variant; from_json dispatches on which key is present
//   PrimitiveSchemaDefinition: base of EnumSchema; exercised through its derived type
//   PromptMessage: no baseline document could be synthesised
//   RequestId: std::variant of string and integer; it has no fields to vary
//   ResourceContents: std::variant; from_json dispatches on text vs blob
//   SamplingMessage: no baseline document could be synthesised
//   SamplingMessageContent: std::variant; from_json accepts a block or a list of blocks
//   ServerCapabilities::TaskRequestsCapability: no census row governs any of its fields
